platform:
    - x86
    - x64

build_script:
  - cmd: cmake -H. -B_build
  - cmd: cmake --build _build --config Release
  - cmd: cd _build
  - cmd: ls
  - cmd: cpack -G WIX
  - cmd: cd ..


deploy:
    description: 'MSI release'
    provider: GitHub
    auth_token:
        secure: pp9qdC6EytDKxk6pAPdSgh8Y1wLLQqQlOYR+/EsyakD2CrhAehyPnA/24HnVr39t
    artifact: ./_build\*.msi
    draft: false
    on:
        branch: master
        APPVEYOR_REPO_TAG: true
